ALTER TYPE "SettlementCycle" ADD VALUE IF NOT EXISTS 'PER_ORDER';
ALTER TYPE "SettlementCycle" ADD VALUE IF NOT EXISTS 'DAILY';
ALTER TYPE "SettlementCycle" ADD VALUE IF NOT EXISTS 'WEEKLY';
ALTER TYPE "SettlementCycle" ADD VALUE IF NOT EXISTS 'PER_PAYOUT';

ALTER TYPE "BillingTrigger" ADD VALUE IF NOT EXISTS 'ORDER_COMPLETED';
ALTER TYPE "BillingTrigger" ADD VALUE IF NOT EXISTS 'PAYOUT_RECEIVED';
ALTER TYPE "BillingTrigger" ADD VALUE IF NOT EXISTS 'PAYMENT_RECEIVED';
