import { z } from "zod";
import { getDashboardData, getInventoryRows } from "@/lib/data";
import { prisma } from "@/lib/prisma";
import { deltas, sumInventory } from "@/lib/inventory";
import { createInventoryMovement, movementInputSchema, reverseInventoryMovement } from "@/lib/services/movements";
import { processGoogleSheetMovementQueue } from "@/lib/google-sheet-movement-queue";
import { runScheduledGoogleSheetSync } from "@/lib/google-sheet-sync";
import type { McpAuth, McpScope } from "@/lib/mcp/oauth";
import { consumeMcpAction, prepareMcpAction } from "@/lib/mcp/confirmation";

type Tool = { name: string; description: string; inputSchema: { type: "object"; properties?: Record<string, unknown>; required?: string[] }; annotations: Record<string, boolean>; scope: McpScope; run: (input: unknown, auth: McpAuth) => Promise<unknown> };
const pagination = { limit: z.coerce.number().int().min(1).max(100).default(30), offset: z.coerce.number().int().min(0).default(0) };
const dateRange = { from: z.string().date().optional(), to: z.string().date().optional() };
function json(result: unknown) {
  const text = JSON.stringify(result, null, 2);
  const value: unknown = JSON.parse(text);
  const structuredContent = value !== null && typeof value === "object" && !Array.isArray(value) ? value : { result: value };
  return { content: [{ type: "text" as const, text }], structuredContent };
}
function number(value: unknown) { return value == null ? null : Number(value); }
function bounds(from?: string, to?: string) { return { ...(from ? { gte: new Date(`${from}T00:00:00.000Z`) } : {}), ...(to ? { lte: new Date(`${to}T23:59:59.999Z`) } : {}) }; }
function tool(definition: Tool) { return definition; }

const tools: Tool[] = [
  tool({ name: "get_dashboard_summary", description: "取得目前庫存、低庫存與銷售的摘要，不含完整資料庫資料。", inputSchema: { type: "object", properties: {} }, annotations: { readOnlyHint: true, idempotentHint: true, destructiveHint: false }, scope: "dashboard:read", run: async () => {
    const data = await getDashboardData();
    return { inventoryProducts: data.inventory.length, lowStock: data.inventory.filter((row) => row.lowStock).length, warehouseUnits: data.inventory.reduce((sum, row) => sum + row.warehouse, 0), consignmentUnits: data.inventory.reduce((sum, row) => sum + row.consignment, 0), salesRecords: data.sales.filter((sale) => sale.countsAsTransaction).length, dateBounds: data.dateBounds };
  } }),
  tool({ name: "search_products", description: "依 SKU、商品名稱或尺寸搜尋商品。", inputSchema: { type: "object", properties: { query: { type: "string" }, limit: { type: "integer", minimum: 1, maximum: 100 } } }, annotations: { readOnlyHint: true, idempotentHint: true, destructiveHint: false }, scope: "products:read", run: async (raw) => {
    const { query = "", limit = 30 } = z.object({ query: z.string().trim().max(160).optional(), limit: pagination.limit.optional() }).parse(raw);
    const rows = await prisma.product.findMany({ where: { active: true, ...(query ? { OR: [{ sku: { contains: query, mode: "insensitive" } }, { name: { contains: query, mode: "insensitive" } }, { size: { contains: query, mode: "insensitive" } }] } : {}) }, orderBy: [{ name: "asc" }, { size: "asc" }], take: limit });
    return rows.map((p) => ({ id: p.id, sku: p.sku, name: p.name, size: p.size, safetyStock: p.safetyStock, listPrice: number(p.listPrice), active: p.active }));
  } }),
  tool({ name: "get_product", description: "取得單一商品主檔與彙總庫存。", inputSchema: { type: "object", required: ["sku"], properties: { sku: { type: "string" } } }, annotations: { readOnlyHint: true, idempotentHint: true, destructiveHint: false }, scope: "products:read", run: async (raw) => {
    const { sku } = z.object({ sku: z.string().trim().min(1).max(80) }).parse(raw); const p = await prisma.product.findUnique({ where: { sku }, include: { movements: true } });
    if (!p) throw new Error("找不到商品"); return { id: p.id, sku: p.sku, name: p.name, size: p.size, safetyStock: p.safetyStock, listPrice: number(p.listPrice), wholesalePrice: number(p.wholesalePrice), unitCost: number(p.unitCost), description: p.description, inventory: sumInventory(p.movements) };
  } }),
  tool({ name: "get_inventory", description: "取得商品的總倉與寄賣庫存；可用 SKU 篩選。", inputSchema: { type: "object", properties: { sku: { type: "string" }, lowStockOnly: { type: "boolean" }, limit: { type: "integer", minimum: 1, maximum: 100 } } }, annotations: { readOnlyHint: true, idempotentHint: true, destructiveHint: false }, scope: "inventory:read", run: async (raw) => {
    const { sku, lowStockOnly, limit } = z.object({ sku: z.string().trim().optional(), lowStockOnly: z.boolean().optional(), limit: pagination.limit.optional() }).parse(raw); let rows = await getInventoryRows();
    if (sku) rows = rows.filter((row) => row.sku === sku); if (lowStockOnly) rows = rows.filter((row) => row.status === "補貨注意"); return rows.slice(0, limit ?? 30);
  } }),
  tool({ name: "get_inventory_by_channel", description: "依通路取得寄賣庫存。", inputSchema: { type: "object", required: ["channel"], properties: { channel: { type: "string" } } }, annotations: { readOnlyHint: true, idempotentHint: true, destructiveHint: false }, scope: "inventory:read", run: async (raw) => {
    const { channel } = z.object({ channel: z.string().trim().min(1) }).parse(raw); const matched = await prisma.channel.findFirst({ where: { OR: [{ id: channel }, { name: channel }] } }); if (!matched) throw new Error("找不到通路");
    const rows = await getInventoryRows(); return { channel: { id: matched.id, name: matched.name, type: matched.type }, inventory: rows.flatMap((row) => row.locations.filter((location) => location.id === matched.id).map((location) => ({ sku: row.sku, name: row.name, size: row.size, quantity: location.quantity }))).filter((row) => row.quantity !== 0) };
  } }),
  tool({ name: "get_low_stock", description: "取得低於或等於安全庫存的商品。", inputSchema: { type: "object", properties: { limit: { type: "integer", minimum: 1, maximum: 100 } } }, annotations: { readOnlyHint: true, idempotentHint: true, destructiveHint: false }, scope: "inventory:read", run: async (raw) => (await getInventoryRows()).filter((row) => row.status === "補貨注意").slice(0, z.object({ limit: pagination.limit.optional() }).parse(raw).limit ?? 30) }),
  tool({ name: "list_channels", description: "列出啟用中的通路。", inputSchema: { type: "object", properties: {} }, annotations: { readOnlyHint: true, idempotentHint: true, destructiveHint: false }, scope: "channels:read", run: async () => (await prisma.channel.findMany({ where: { active: true }, orderBy: { name: "asc" } })).map((channel) => ({ id: channel.id, name: channel.name, type: channel.type })) }),
  tool({ name: "list_inventory_movements", description: "依 SKU、通路、類型及日期區間查詢庫存異動，預設最多 30 筆。", inputSchema: { type: "object", properties: { sku: { type: "string" }, channelId: { type: "string" }, type: { type: "string" }, from: { type: "string", format: "date" }, to: { type: "string", format: "date" }, limit: { type: "integer", minimum: 1, maximum: 100 }, offset: { type: "integer", minimum: 0 } } }, annotations: { readOnlyHint: true, idempotentHint: true, destructiveHint: false }, scope: "movements:read", run: async (raw) => {
    const input = z.object({ sku: z.string().optional(), channelId: z.string().optional(), type: z.enum(["RECEIVE", "SHIP", "CONSIGN_OUT", "CONSIGN_RETURN", "CONSIGN_SOLD", "BUYOUT", "DEFECT", "ADJUSTMENT"]).optional(), ...dateRange, ...pagination }).parse(raw);
    const rows = await prisma.stockMovement.findMany({ where: { ...(input.sku ? { product: { sku: input.sku } } : {}), ...(input.channelId ? { channelId: input.channelId } : {}), ...(input.type ? { type: input.type } : {}), ...(input.from || input.to ? { occurredAt: bounds(input.from, input.to) } : {}) }, include: { product: true, channel: true }, orderBy: [{ occurredAt: "desc" }, { id: "desc" }], take: input.limit, skip: input.offset });
    return rows.map((m) => ({ id: m.id, occurredAt: m.occurredAt, type: m.type, quantity: m.quantity, sku: m.product.sku, product: m.product.name, channel: m.channel?.name ?? null, unitPrice: number(m.unitPrice), note: m.note, reversedAt: m.reversedAt, reversalOfId: m.reversalOfId }));
  } }),
  tool({ name: "get_inventory_movement", description: "取得一筆庫存異動。", inputSchema: { type: "object", required: ["id"], properties: { id: { type: "string" } } }, annotations: { readOnlyHint: true, idempotentHint: true, destructiveHint: false }, scope: "movements:read", run: async (raw) => {
    const { id } = z.object({ id: z.string().min(1) }).parse(raw); const m = await prisma.stockMovement.findUnique({ where: { id }, include: { product: true, channel: true, reversal: true } }); if (!m) throw new Error("找不到異動"); return { id: m.id, occurredAt: m.occurredAt, type: m.type, quantity: m.quantity, sku: m.product.sku, product: m.product.name, channel: m.channel?.name ?? null, unitPrice: number(m.unitPrice), referenceNo: m.referenceNo, note: m.note, reversedAt: m.reversedAt, reversalId: m.reversal?.id ?? null };
  } }),
  tool({ name: "get_sales_summary", description: "取得指定日期區間的銷售量與營收摘要。", inputSchema: { type: "object", properties: { from: { type: "string", format: "date" }, to: { type: "string", format: "date" } } }, annotations: { readOnlyHint: true, idempotentHint: true, destructiveHint: false }, scope: "sales:read", run: async (raw) => {
    const { from, to } = z.object(dateRange).parse(raw); const rows = await prisma.stockMovement.findMany({ where: { type: { in: ["SHIP", "CONSIGN_SOLD", "BUYOUT"] }, ...(from || to ? { occurredAt: bounds(from, to) } : {}) } }); const valid = rows.filter((m) => m.quantity > 0 && !m.reversedAt && !m.reversalOfId); return { transactions: valid.length, quantity: valid.reduce((sum, m) => sum + m.quantity, 0), revenue: valid.reduce((sum, m) => sum + Number(m.unitPrice ?? 0) * m.quantity, 0) };
  } }),
  tool({ name: "get_sales_by_channel", description: "依通路取得指定日期區間的銷售摘要。", inputSchema: { type: "object", properties: { from: { type: "string", format: "date" }, to: { type: "string", format: "date" } } }, annotations: { readOnlyHint: true, idempotentHint: true, destructiveHint: false }, scope: "sales:read", run: async (raw) => {
    const { from, to } = z.object(dateRange).parse(raw); const rows = await prisma.stockMovement.findMany({ where: { type: { in: ["SHIP", "CONSIGN_SOLD", "BUYOUT"] }, ...(from || to ? { occurredAt: bounds(from, to) } : {}) }, include: { channel: true } }); const totals = new Map<string, { channel: string; quantity: number; revenue: number }>(); for (const m of rows.filter((m) => m.quantity > 0 && !m.reversedAt && !m.reversalOfId)) { const key = m.channelId ?? "unassigned"; const current = totals.get(key) ?? { channel: m.channel?.name ?? "未指定", quantity: 0, revenue: 0 }; current.quantity += m.quantity; current.revenue += Number(m.unitPrice ?? 0) * m.quantity; totals.set(key, current); } return [...totals.values()].sort((a, b) => b.revenue - a.revenue);
  } }),
  tool({ name: "get_sheet_sync_status", description: "取得 Google Sheet 連線與最近同步狀態，不含任何憑證。", inputSchema: { type: "object", properties: {} }, annotations: { readOnlyHint: true, idempotentHint: true, destructiveHint: false }, scope: "sync:read", run: async () => {
    const [connection, latest, queue] = await Promise.all([prisma.googleSheetConnection.findFirst({ orderBy: { updatedAt: "desc" } }), prisma.googleSheetSyncRun.findFirst({ orderBy: { createdAt: "desc" } }), prisma.googleSheetMovementQueue.groupBy({ by: ["status"], _count: { _all: true } })]); return { connection: connection ? { spreadsheetTitle: connection.spreadsheetTitle, lastTestedAt: connection.lastTestedAt, lastTestStatus: connection.lastTestStatus, automaticSyncEnabled: connection.automaticSyncEnabled } : null, latestRun: latest ? { status: latest.status, mode: latest.mode, createdAt: latest.createdAt, completedAt: latest.completedAt, error: latest.error } : null, movementQueue: queue.map((item) => ({ status: item.status, count: item._count._all })) };
  } }),
  tool({ name: "list_failed_sync_jobs", description: "列出最近失敗的 Google Sheet 同步工作，最多 100 筆。", inputSchema: { type: "object", properties: { limit: { type: "integer", minimum: 1, maximum: 100 } } }, annotations: { readOnlyHint: true, idempotentHint: true, destructiveHint: false }, scope: "sync:read", run: async (raw) => { const { limit } = z.object({ limit: pagination.limit.optional() }).parse(raw); const rows = await prisma.googleSheetMovementQueue.findMany({ where: { status: "FAILED" }, include: { movement: { include: { product: true } } }, orderBy: { updatedAt: "desc" }, take: limit ?? 30 }); return rows.map((job) => ({ id: job.id, movementId: job.movementId, sku: job.movement.product.sku, attempts: job.attempts, lastError: job.lastError, updatedAt: job.updatedAt })); } }),
  tool({ name: "create_inventory_movement", description: "建立庫存異動的兩階段操作。第一次不帶 confirmationToken 只回傳 preview；向使用者取得明確確認後，使用完全相同參數並帶回 token 才會寫入。", inputSchema: { type: "object", required: ["sku", "type", "quantity"], properties: { sku: { type: "string" }, type: { type: "string", enum: ["RECEIVE", "SHIP", "CONSIGN_OUT", "CONSIGN_RETURN", "CONSIGN_SOLD", "BUYOUT", "DEFECT", "ADJUSTMENT"] }, quantity: { type: "integer", minimum: 1 }, channelId: { type: "string" }, unitPrice: { type: "number", minimum: 0 }, note: { type: "string" }, referenceNo: { type: "string" }, occurredAt: { type: "string", format: "date-time" }, confirmationToken: { type: "string", description: "第一次 preview 回傳的短效單次 token；只有使用者確認後才能傳入。" } } }, annotations: { readOnlyHint: false, idempotentHint: false, destructiveHint: false }, scope: "inventory:write", run: async (raw, auth) => {
    const input = z.object({ sku: z.string().trim().min(1).max(80), type: z.enum(["RECEIVE", "SHIP", "CONSIGN_OUT", "CONSIGN_RETURN", "CONSIGN_SOLD", "BUYOUT", "DEFECT", "ADJUSTMENT"]), quantity: z.coerce.number().int().positive(), channelId: z.string().optional(), unitPrice: z.coerce.number().min(0).optional(), note: z.string().trim().max(500).optional(), referenceNo: z.string().trim().max(120).optional(), occurredAt: z.coerce.date().optional(), confirmationToken: z.string().optional() }).parse(raw); const { confirmationToken, ...command } = input; const payload = JSON.parse(JSON.stringify({ ...command, occurredAt: command.occurredAt?.toISOString() })); const product = await prisma.product.findUnique({ where: { sku: input.sku } }); if (!product) throw new Error("找不到商品"); if (!confirmationToken) { const existing = await prisma.stockMovement.findMany({ where: { productId: product.id } }); const current = sumInventory(existing); const delta = deltas(input.type, input.quantity); return prepareMcpAction("create_inventory_movement", payload, auth, { movement: payload, product: { sku: product.sku, name: product.name, size: product.size }, current, projected: { warehouse: current.warehouse + delta.warehouse, consignment: current.consignment + delta.consignment }, note: "commit 時會重新執行全部角色、scope、通路、價格與庫存驗證。" }); } await consumeMcpAction("create_inventory_movement", confirmationToken, payload, auth); const created = await createInventoryMovement(movementInputSchema.parse({ ...command, productId: product.id }), { userId: auth.userId, role: auth.role, source: "MCP", connectionId: auth.connectionId, clientId: auth.clientId }); const totals = sumInventory(await prisma.stockMovement.findMany({ where: { productId: product.id } })); return { committed: true, movement: { id: created.id, sku: product.sku, type: created.type, quantity: created.quantity, channelId: created.channelId }, impact: { resultingWarehouse: totals.warehouse, resultingConsignment: totals.consignment, googleSheetSyncQueued: true } };
  } }),
  tool({ name: "reverse_inventory_movement", description: "沖銷異動的兩階段操作。第一次只回傳 preview；使用者明確確認後以相同 movementId 與 confirmationToken 再呼叫才會沖銷。", inputSchema: { type: "object", required: ["movementId"], properties: { movementId: { type: "string" }, confirmationToken: { type: "string" } } }, annotations: { readOnlyHint: false, idempotentHint: false, destructiveHint: true }, scope: "movements:reverse", run: async (raw, auth) => { const { movementId, confirmationToken } = z.object({ movementId: z.string().min(1), confirmationToken: z.string().optional() }).parse(raw); const payload = { movementId }; if (!confirmationToken) { const movement = await prisma.stockMovement.findUnique({ where: { id: movementId }, include: { product: true, channel: true, reversal: true } }); if (!movement || movement.reversal || movement.reversedAt || movement.reversalOfId) throw new Error("找不到可沖銷的異動"); return prepareMcpAction("reverse_inventory_movement", payload, auth, { movementId, sku: movement.product.sku, product: movement.product.name, channel: movement.channel?.name ?? null, type: movement.type, quantity: movement.quantity, occurredAt: movement.occurredAt }); } await consumeMcpAction("reverse_inventory_movement", confirmationToken, payload, auth); const reversal = await reverseInventoryMovement(movementId, { userId: auth.userId, role: auth.role, source: "MCP", connectionId: auth.connectionId, clientId: auth.clientId }); return { committed: true, reversedMovementId: movementId, reversalMovementId: reversal.id, type: reversal.type, quantity: reversal.quantity, googleSheetSyncQueued: true }; } }),
  tool({ name: "run_sheet_sync", description: "立即同步的兩階段操作。第一次只回傳 preview；使用者明確確認後帶 confirmationToken 再呼叫才會執行。", inputSchema: { type: "object", properties: { confirmationToken: { type: "string" } } }, annotations: { readOnlyHint: false, idempotentHint: false, destructiveHint: false }, scope: "sync:run", run: async (raw, auth) => { if (auth.role !== "ADMIN") throw new Error("FORBIDDEN"); const { confirmationToken } = z.object({ confirmationToken: z.string().optional() }).parse(raw); const payload = {}; if (!confirmationToken) return prepareMcpAction("run_sheet_sync", payload, auth, { action: "立即執行 Google Sheet 全量同步與 movement queue 處理" }); await consumeMcpAction("run_sheet_sync", confirmationToken, payload, auth); const run = await runScheduledGoogleSheetSync(undefined, auth.userId); const queue = await processGoogleSheetMovementQueue(); await prisma.auditLog.create({ data: { userId: auth.userId, action: "MCP_SHEET_SYNC_RUN", entityType: "GoogleSheetSyncRun", metadata: { source: "MCP", connectionId: auth.connectionId, clientId: auth.clientId } } }); return { committed: true, run, movementQueue: queue }; } }),
];

function roleAllowsTool(tool: Tool, role: McpAuth["role"]) {
  if (role === "ADMIN") return true;
  if (role === "STAFF") return tool.scope !== "sync:run";
  return tool.annotations.readOnlyHint === true;
}

export function listMcpTools(auth?: McpAuth) {
  return tools
    .filter((definition) => !auth || (auth.scopes.includes(definition.scope) && roleAllowsTool(definition, auth.role)))
    .map(({ name, description, inputSchema, annotations }) => ({ name, description, inputSchema, annotations }));
}
export async function callMcpTool(name: string, input: unknown, auth: McpAuth) { const definition = tools.find((item) => item.name === name); if (!definition) throw new Error("找不到 MCP tool"); if (!auth.scopes.includes(definition.scope)) throw new Error("OAuth scope 不足"); if (!roleAllowsTool(definition, auth.role)) throw new Error("ERP 角色權限不足"); return json(await definition.run(input ?? {}, auth)); }
